name: heroku-deploy
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.4.6
              with:
                  buildpack: "https://buildpack-registry.s3.amazonaws.com/buildpacks/mars/create-react-app.tgz"
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: "cp-buddy"
                  heroku_email: "ankit.kumar.cse19@iitbhu.ac.in"

            - name: Run a one-line script
              run: echo "Deployed successfully"
